name: savannatreeai

dependencies:
  - matplotlib
  - opencv
  - python=3.6.5
  - Pillow
  - geopandas
  - geojson
  - json
  - os
  - rasterio
  - numpy
  - pip
  - pip:
    - azure-cognitiveservices-vision-customvision
    - azure-functions
    - azure-storage
    - azureml-sdk[notebooks,automl]
    - ffmpeg-python
    - python-dotenv


